package cn.ziroom.mapper;

import com.sunshulin.service.GeneralCriteria;

/**
 * 小区实体
 * 
 * @author Administrator
 * 
 */
public class Area extends GeneralCriteria {

	private static final long serialVersionUID = 6915146350343990915L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.AREA_ID
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer areaId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.CITY_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String cityCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BUSINESS_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String businessCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.SUBWAY_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String subwayCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.SUBWAY_STATION_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String subwayStationCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.CIRCLE_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String circleCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.AREA_SPELLING_FULL
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String areaSpellingFull;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.AREA_SPELLING_SHORT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String areaSpellingShort;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.AREA_ALIAS
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String areaAlias;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.AREA_NAME
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String areaName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.FIRST_LETTER
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String firstLetter;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.AREA_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String areaCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.AREA_ADDRESS
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String areaAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.PROPERTIES_COMPANY
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String propertiesCompany;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.PROPERTIES_TELPHONE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String propertiesTelphone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.PROPERTIES_TYPE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String propertiesType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.STEP_TO_STATION
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String stepToStation;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BUILDING_AMOUNT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer buildingAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BUS_LINES
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String busLines;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BUILD_END_YEAR
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildEndYear;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.POSITION
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String position;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.GROUND_AREA
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float groundArea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.CAR_NUM
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer carNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.CUBAGE_RATE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float cubageRate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BUS_STATION
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String busStation;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.HOUSE_AMOUNT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer houseAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BUILD_BEGIN_YEAR
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildBeginYear;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BUILD_STYLE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildStyle;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BUILD_SIZE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float buildSize;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.VIRESCENCE_RATE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float virescenceRate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BAIDU_LONGITUDE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float baiduLongitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.BAIDU_LATITUDE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float baiduLatitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.GOOGLE_LONGITUDE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float googleLongitude;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_area.GOOGLE_LATITUDE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float googleLatitude;

	public Integer getAreaId() {
		return areaId;
	}

	public void setAreaId(Integer areaId) {
		this.areaId = areaId;
	}

	public String getCityCode() {
		return cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode == null ? null : cityCode.trim();
	}

	public String getBusinessCode() {
		return businessCode;
	}

	public void setBusinessCode(String businessCode) {
		this.businessCode = businessCode == null ? null : businessCode.trim();
	}

	public String getSubwayCode() {
		return subwayCode;
	}

	public void setSubwayCode(String subwayCode) {
		this.subwayCode = subwayCode == null ? null : subwayCode.trim();
	}

	public String getSubwayStationCode() {
		return subwayStationCode;
	}

	public void setSubwayStationCode(String subwayStationCode) {
		this.subwayStationCode = subwayStationCode == null ? null : subwayStationCode.trim();
	}

	public String getCircleCode() {
		return circleCode;
	}

	public void setCircleCode(String circleCode) {
		this.circleCode = circleCode == null ? null : circleCode.trim();
	}

	public String getAreaSpellingFull() {
		return areaSpellingFull;
	}

	public void setAreaSpellingFull(String areaSpellingFull) {
		this.areaSpellingFull = areaSpellingFull == null ? null : areaSpellingFull.trim();
	}

	public String getAreaSpellingShort() {
		return areaSpellingShort;
	}

	public void setAreaSpellingShort(String areaSpellingShort) {
		this.areaSpellingShort = areaSpellingShort == null ? null : areaSpellingShort.trim();
	}

	public String getAreaAlias() {
		return areaAlias;
	}

	public void setAreaAlias(String areaAlias) {
		this.areaAlias = areaAlias == null ? null : areaAlias.trim();
	}

	public String getAreaName() {
		return areaName;
	}

	public void setAreaName(String areaName) {
		this.areaName = areaName == null ? null : areaName.trim();
	}

	public String getFirstLetter() {
		return firstLetter;
	}

	public void setFirstLetter(String firstLetter) {
		this.firstLetter = firstLetter == null ? null : firstLetter.trim();
	}

	public String getAreaCode() {
		return areaCode;
	}

	public void setAreaCode(String areaCode) {
		this.areaCode = areaCode == null ? null : areaCode.trim();
	}

	public String getAreaAddress() {
		return areaAddress;
	}

	public void setAreaAddress(String areaAddress) {
		this.areaAddress = areaAddress == null ? null : areaAddress.trim();
	}

	public String getPropertiesCompany() {
		return propertiesCompany;
	}

	public void setPropertiesCompany(String propertiesCompany) {
		this.propertiesCompany = propertiesCompany == null ? null : propertiesCompany.trim();
	}

	public String getPropertiesTelphone() {
		return propertiesTelphone;
	}

	public void setPropertiesTelphone(String propertiesTelphone) {
		this.propertiesTelphone = propertiesTelphone == null ? null : propertiesTelphone.trim();
	}

	public String getPropertiesType() {
		return propertiesType;
	}

	public void setPropertiesType(String propertiesType) {
		this.propertiesType = propertiesType == null ? null : propertiesType.trim();
	}

	public String getStepToStation() {
		return stepToStation;
	}

	public void setStepToStation(String stepToStation) {
		this.stepToStation = stepToStation == null ? null : stepToStation.trim();
	}

	public Integer getBuildingAmount() {
		return buildingAmount;
	}

	public void setBuildingAmount(Integer buildingAmount) {
		this.buildingAmount = buildingAmount;
	}

	public String getBusLines() {
		return busLines;
	}

	public void setBusLines(String busLines) {
		this.busLines = busLines == null ? null : busLines.trim();
	}

	public String getBuildEndYear() {
		return buildEndYear;
	}

	public void setBuildEndYear(String buildEndYear) {
		this.buildEndYear = buildEndYear == null ? null : buildEndYear.trim();
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position == null ? null : position.trim();
	}

	public Float getGroundArea() {
		return groundArea;
	}

	public void setGroundArea(Float groundArea) {
		this.groundArea = groundArea;
	}

	public Integer getCarNum() {
		return carNum;
	}

	public void setCarNum(Integer carNum) {
		this.carNum = carNum;
	}

	public Float getCubageRate() {
		return cubageRate;
	}

	public void setCubageRate(Float cubageRate) {
		this.cubageRate = cubageRate;
	}

	public String getBusStation() {
		return busStation;
	}

	public void setBusStation(String busStation) {
		this.busStation = busStation == null ? null : busStation.trim();
	}

	public Integer getHouseAmount() {
		return houseAmount;
	}

	public void setHouseAmount(Integer houseAmount) {
		this.houseAmount = houseAmount;
	}

	public String getBuildBeginYear() {
		return buildBeginYear;
	}

	public void setBuildBeginYear(String buildBeginYear) {
		this.buildBeginYear = buildBeginYear == null ? null : buildBeginYear.trim();
	}

	public String getBuildStyle() {
		return buildStyle;
	}

	public void setBuildStyle(String buildStyle) {
		this.buildStyle = buildStyle == null ? null : buildStyle.trim();
	}

	public Float getBuildSize() {
		return buildSize;
	}

	public void setBuildSize(Float buildSize) {
		this.buildSize = buildSize;
	}

	public Float getVirescenceRate() {
		return virescenceRate;
	}

	public void setVirescenceRate(Float virescenceRate) {
		this.virescenceRate = virescenceRate;
	}

	public Float getBaiduLongitude() {
		return baiduLongitude;
	}

	public void setBaiduLongitude(Float baiduLongitude) {
		this.baiduLongitude = baiduLongitude;
	}

	public Float getBaiduLatitude() {
		return baiduLatitude;
	}

	public void setBaiduLatitude(Float baiduLatitude) {
		this.baiduLatitude = baiduLatitude;
	}

	public Float getGoogleLongitude() {
		return googleLongitude;
	}

	public void setGoogleLongitude(Float googleLongitude) {
		this.googleLongitude = googleLongitude;
	}

	public Float getGoogleLatitude() {
		return googleLatitude;
	}

	public void setGoogleLatitude(Float googleLatitude) {
		this.googleLatitude = googleLatitude;
	}
}