package cn.ziroom.mapper;

import com.sunshulin.service.GeneralCriteria;

/**
 * 房屋实体
 * 
 * @author Administrator
 * 
 */
public class Building extends GeneralCriteria {

	private static final long serialVersionUID = 8161041881539908745L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_ID
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer buildingId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_NUMBER
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildingNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildingCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.CITY_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String cityCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUSSNESS_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String bussnessCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.CUSTOMER_ID
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer customerId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.FLOOR
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer floor;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.TOTAL_FLOOR
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer totalFloor;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_CERTIFICATE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildingCertificate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_TYPE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildingType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.ELEVATOR
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String elevator;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_AREA
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float buildingArea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.USE_AREA
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Float useArea;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.HEATING
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String heating;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.UNIT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String unit;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.ORIENTATION
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String orientation;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.EXECUTIVE_ADDRESS
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String executiveAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.COOKROOM_AMOUNT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer cookroomAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.PROVIDE_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String provideCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.PROPERTY_ADDRESS
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String propertyAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_LEVEL
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildingLevel;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BALCONY_AMOUNT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer balconyAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BEDROOM_AMOUNT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer bedroomAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_FEATURE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildingFeature;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_STRUCTURE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildingStructure;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.GARDEN_AMOUNT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer gardenAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.DISTRICT_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String districtCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.BUILDING_STATUS
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String buildingStatus;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.PARLOR_AMOUNT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer parlorAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.TOILET_AMOUNT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer toiletAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.HOUSE_NUMBER
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String houseNumber;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.TERRACE_AMOUNT
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer terraceAmount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.DECORATE_TYPE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String decorateType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_building.EXTENT_ITEM
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String extentItem;
	
	private Area area = new Area();

	public Integer getBuildingId() {
		return buildingId;
	}

	public void setBuildingId(Integer buildingId) {
		this.buildingId = buildingId;
	}

	public String getBuildingNumber() {
		return buildingNumber;
	}

	public void setBuildingNumber(String buildingNumber) {
		this.buildingNumber = buildingNumber == null ? null : buildingNumber.trim();
	}

	public String getBuildingCode() {
		return buildingCode;
	}

	public void setBuildingCode(String buildingCode) {
		this.buildingCode = buildingCode == null ? null : buildingCode.trim();
	}

	public String getCityCode() {
		return cityCode;
	}

	public void setCityCode(String cityCode) {
		this.cityCode = cityCode == null ? null : cityCode.trim();
	}

	public String getBussnessCode() {
		return bussnessCode;
	}

	public void setBussnessCode(String bussnessCode) {
		this.bussnessCode = bussnessCode == null ? null : bussnessCode.trim();
	}

	public Integer getCustomerId() {
		return customerId;
	}

	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	public Integer getFloor() {
		return floor;
	}

	public void setFloor(Integer floor) {
		this.floor = floor;
	}

	public Integer getTotalFloor() {
		return totalFloor;
	}

	public void setTotalFloor(Integer totalFloor) {
		this.totalFloor = totalFloor;
	}

	public String getBuildingCertificate() {
		return buildingCertificate;
	}

	public void setBuildingCertificate(String buildingCertificate) {
		this.buildingCertificate = buildingCertificate == null ? null : buildingCertificate.trim();
	}

	public String getBuildingType() {
		return buildingType;
	}

	public void setBuildingType(String buildingType) {
		this.buildingType = buildingType == null ? null : buildingType.trim();
	}

	public String getElevator() {
		return elevator;
	}

	public void setElevator(String elevator) {
		this.elevator = elevator == null ? null : elevator.trim();
	}

	public Float getBuildingArea() {
		return buildingArea;
	}

	public void setBuildingArea(Float buildingArea) {
		this.buildingArea = buildingArea;
	}

	public Float getUseArea() {
		return useArea;
	}

	public void setUseArea(Float useArea) {
		this.useArea = useArea;
	}

	public String getHeating() {
		return heating;
	}

	public void setHeating(String heating) {
		this.heating = heating == null ? null : heating.trim();
	}

	public String getUnit() {
		return unit;
	}

	public void setUnit(String unit) {
		this.unit = unit == null ? null : unit.trim();
	}

	public String getOrientation() {
		return orientation;
	}

	public void setOrientation(String orientation) {
		this.orientation = orientation == null ? null : orientation.trim();
	}

	public String getExecutiveAddress() {
		return executiveAddress;
	}

	public void setExecutiveAddress(String executiveAddress) {
		this.executiveAddress = executiveAddress == null ? null : executiveAddress.trim();
	}

	public Integer getCookroomAmount() {
		return cookroomAmount;
	}

	public void setCookroomAmount(Integer cookroomAmount) {
		this.cookroomAmount = cookroomAmount;
	}

	public String getProvideCode() {
		return provideCode;
	}

	public void setProvideCode(String provideCode) {
		this.provideCode = provideCode == null ? null : provideCode.trim();
	}

	public String getPropertyAddress() {
		return propertyAddress;
	}

	public void setPropertyAddress(String propertyAddress) {
		this.propertyAddress = propertyAddress == null ? null : propertyAddress.trim();
	}

	public String getBuildingLevel() {
		return buildingLevel;
	}

	public void setBuildingLevel(String buildingLevel) {
		this.buildingLevel = buildingLevel == null ? null : buildingLevel.trim();
	}

	public Integer getBalconyAmount() {
		return balconyAmount;
	}

	public void setBalconyAmount(Integer balconyAmount) {
		this.balconyAmount = balconyAmount;
	}

	public Integer getBedroomAmount() {
		return bedroomAmount;
	}

	public void setBedroomAmount(Integer bedroomAmount) {
		this.bedroomAmount = bedroomAmount;
	}

	public String getBuildingFeature() {
		return buildingFeature;
	}

	public void setBuildingFeature(String buildingFeature) {
		this.buildingFeature = buildingFeature == null ? null : buildingFeature.trim();
	}

	public String getBuildingStructure() {
		return buildingStructure;
	}

	public void setBuildingStructure(String buildingStructure) {
		this.buildingStructure = buildingStructure == null ? null : buildingStructure.trim();
	}

	public Integer getGardenAmount() {
		return gardenAmount;
	}

	public void setGardenAmount(Integer gardenAmount) {
		this.gardenAmount = gardenAmount;
	}

	public String getDistrictCode() {
		return districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode == null ? null : districtCode.trim();
	}

	public String getBuildingStatus() {
		return buildingStatus;
	}

	public void setBuildingStatus(String buildingStatus) {
		this.buildingStatus = buildingStatus == null ? null : buildingStatus.trim();
	}

	public Integer getParlorAmount() {
		return parlorAmount;
	}

	public void setParlorAmount(Integer parlorAmount) {
		this.parlorAmount = parlorAmount;
	}

	public Integer getToiletAmount() {
		return toiletAmount;
	}

	public void setToiletAmount(Integer toiletAmount) {
		this.toiletAmount = toiletAmount;
	}

	public String getHouseNumber() {
		return houseNumber;
	}

	public void setHouseNumber(String houseNumber) {
		this.houseNumber = houseNumber == null ? null : houseNumber.trim();
	}

	public Integer getTerraceAmount() {
		return terraceAmount;
	}

	public void setTerraceAmount(Integer terraceAmount) {
		this.terraceAmount = terraceAmount;
	}

	public String getDecorateType() {
		return decorateType;
	}

	public void setDecorateType(String decorateType) {
		this.decorateType = decorateType == null ? null : decorateType.trim();
	}

	public String getExtentItem() {
		return extentItem;
	}

	public void setExtentItem(String extentItem) {
		this.extentItem = extentItem == null ? null : extentItem.trim();
	}

	public Area getArea() {
		return area;
	}

	public void setArea(Area area) {
		this.area = area;
	}
}