package cn.ziroom.mapper;

import com.sunshulin.service.GeneralCriteria;

/**
 * 城市实体
 * @author Administrator
 *
 */
public class City extends GeneralCriteria {

	private static final long serialVersionUID = 8227544199385224912L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.CITY_ID
     *
     * @mbggenerated Tue Nov 22 10:42:22 CST 2011
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.PROVINCE_ID
     *
     * @mbggenerated Tue Nov 22 10:42:22 CST 2011
     */
    private Integer provinceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.CITY_NAME
     *
     * @mbggenerated Tue Nov 22 10:42:22 CST 2011
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.CITY_PINYIN
     *
     * @mbggenerated Tue Nov 22 10:42:22 CST 2011
     */
    private String cityPinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_city.CITY_CODE
     *
     * @mbggenerated Tue Nov 22 10:42:22 CST 2011
     */
    private String cityCode;

    public Integer getCityId() {
        return cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    public Integer getProvinceId() {
        return provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    public String getCityPinyin() {
        return cityPinyin;
    }

    public void setCityPinyin(String cityPinyin) {
        this.cityPinyin = cityPinyin == null ? null : cityPinyin.trim();
    }

    public String getCityCode() {
        return cityCode;
    }

    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }
}