package cn.ziroom.mapper;

import com.sunshulin.service.GeneralCriteria;

/**
 * 城区实体
 * 
 * @author Administrator
 * 
 */
public class District extends GeneralCriteria {

	private static final long serialVersionUID = -9111494960039646214L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district.DISTRICT_ID
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer districtId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district.CITY_ID
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer cityId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district.DISTRICT_NAME
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String districtName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district.DISTRICT_PINYIN
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String districtPinyin;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_district.DISTRICT_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String districtCode;

	public Integer getDistrictId() {
		return districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public String getDistrictName() {
		return districtName;
	}

	public void setDistrictName(String districtName) {
		this.districtName = districtName == null ? null : districtName.trim();
	}

	public String getDistrictPinyin() {
		return districtPinyin;
	}

	public void setDistrictPinyin(String districtPinyin) {
		this.districtPinyin = districtPinyin == null ? null : districtPinyin.trim();
	}

	public String getDistrictCode() {
		return districtCode;
	}

	public void setDistrictCode(String districtCode) {
		this.districtCode = districtCode == null ? null : districtCode.trim();
	}
}