package cn.ziroom.mapper;

import com.sunshulin.service.GeneralCriteria;

/**
 * 地铁站点实体
 * 
 * @author Administrator
 * 
 */
public class SubwayStation extends GeneralCriteria {

	private static final long serialVersionUID = 337473556330019225L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.STATION_ID
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer stationId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.SUBWAY_ID
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private Integer subwayId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.STATION_NAME
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String stationName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.STATION_CODE
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String stationCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_subway_station.STATION_DESC
	 * 
	 * @mbggenerated Tue Nov 22 10:42:22 CST 2011
	 */
	private String stationDesc;

	public Integer getStationId() {
		return stationId;
	}

	public void setStationId(Integer stationId) {
		this.stationId = stationId;
	}

	public Integer getSubwayId() {
		return subwayId;
	}

	public void setSubwayId(Integer subwayId) {
		this.subwayId = subwayId;
	}

	public String getStationName() {
		return stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName == null ? null : stationName.trim();
	}

	public String getStationCode() {
		return stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode == null ? null : stationCode.trim();
	}

	public String getStationDesc() {
		return stationDesc;
	}

	public void setStationDesc(String stationDesc) {
		this.stationDesc = stationDesc == null ? null : stationDesc.trim();
	}
}