package cn.ziroom.basic.mapper;

import java.util.ArrayList;
import java.util.List;

import com.sunshulin.service.GeneralCriteria;

/**
 * 数据字典实体
 * 
 * @author Administrator
 * 
 */
public class Dict extends GeneralCriteria {

	private static final long serialVersionUID = -1291581791323289343L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_DICT.DICT_ID
	 * 
	 * @mbggenerated Fri Nov 25 10:57:02 CST 2011
	 */
	private Integer dictId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_DICT.DICT_TYPE
	 * 
	 * @mbggenerated Fri Nov 25 10:57:02 CST 2011
	 */
	private String dictType;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_DICT.DICT_NAME
	 * 
	 * @mbggenerated Fri Nov 25 10:57:02 CST 2011
	 */
	private String dictName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_DICT.DICT_VALUE
	 * 
	 * @mbggenerated Fri Nov 25 10:57:02 CST 2011
	 */
	private String dictValue;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_DICT.DICT_ORDER
	 * 
	 * @mbggenerated Fri Nov 25 10:57:02 CST 2011
	 */
	private String dictOrder;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_DICT.DICT_STATUS
	 * 
	 * @mbggenerated Fri Nov 25 10:57:02 CST 2011
	 */
	private String dictStatus;

	/**
	 * 按分类的数字字典列表
	 */
	private List<Dict> dictList = new ArrayList<Dict>();

	public Integer getDictId() {
		return dictId;
	}

	public void setDictId(Integer dictId) {
		this.dictId = dictId;
	}

	public String getDictType() {
		return dictType;
	}

	public void setDictType(String dictType) {
		this.dictType = dictType == null ? null : dictType.trim();
	}

	public String getDictName() {
		return dictName;
	}

	public void setDictName(String dictName) {
		this.dictName = dictName == null ? null : dictName.trim();
	}

	public String getDictValue() {
		return dictValue;
	}

	public void setDictValue(String dictValue) {
		this.dictValue = dictValue == null ? null : dictValue.trim();
	}

	public String getDictOrder() {
		return dictOrder;
	}

	public void setDictOrder(String dictOrder) {
		this.dictOrder = dictOrder == null ? null : dictOrder.trim();
	}

	public String getDictStatus() {
		return dictStatus;
	}

	public void setDictStatus(String dictStatus) {
		this.dictStatus = dictStatus == null ? null : dictStatus.trim();
	}

	public List<Dict> getDictList() {
		return dictList;
	}

	public void setDictList(List<Dict> dictList) {
		this.dictList = dictList;
	}
}